// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5R07pfvsiGZnyLAFCENn3FOf6CBgkkew',
    appId: '1:239885424042:web:d8c03ca082efe2779287d3',
    messagingSenderId: '239885424042',
    projectId: 'myskillappdb',
    authDomain: 'myskillappdb.firebaseapp.com',
    storageBucket: 'myskillappdb.firebasestorage.app',
    measurementId: 'G-ZWRKV0VGF9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7TpooTgcCDjddD6jQm0ueU2VPioOGcSo',
    appId: '1:239885424042:android:db88a070a9a1e7bb9287d3',
    messagingSenderId: '239885424042',
    projectId: 'myskillappdb',
    storageBucket: 'myskillappdb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaYvKaKcPvBUDKQs7p--QAybOO4eMKars',
    appId: '1:239885424042:ios:a1080a276d6d68119287d3',
    messagingSenderId: '239885424042',
    projectId: 'myskillappdb',
    storageBucket: 'myskillappdb.firebasestorage.app',
    iosBundleId: 'com.example.myskillsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaYvKaKcPvBUDKQs7p--QAybOO4eMKars',
    appId: '1:239885424042:ios:a1080a276d6d68119287d3',
    messagingSenderId: '239885424042',
    projectId: 'myskillappdb',
    storageBucket: 'myskillappdb.firebasestorage.app',
    iosBundleId: 'com.example.myskillsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5R07pfvsiGZnyLAFCENn3FOf6CBgkkew',
    appId: '1:239885424042:web:0ee72b394edc864d9287d3',
    messagingSenderId: '239885424042',
    projectId: 'myskillappdb',
    authDomain: 'myskillappdb.firebaseapp.com',
    storageBucket: 'myskillappdb.firebasestorage.app',
    measurementId: 'G-QRYRRSNSS5',
  );
}
